// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD--h9D9L_-B7bfjCDY9nOdyTVJCdp-PN4',
    appId: '1:170154968652:web:1fdc0fa43eaf6f0b05d6e9',
    messagingSenderId: '170154968652',
    projectId: 'smart-expense-tracker-86619',
    authDomain: 'smart-expense-tracker-86619.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-86619.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9qfAliUgWgJp9QP8BTjn4oFIT2gimXtY',
    appId: '1:170154968652:android:d5d5307df482436f05d6e9',
    messagingSenderId: '170154968652',
    projectId: 'smart-expense-tracker-86619',
    storageBucket: 'smart-expense-tracker-86619.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChqJzuKcK1Do_BpbpuruA4LPF_xAS2Qpw',
    appId: '1:170154968652:ios:528b111ebd294d7005d6e9',
    messagingSenderId: '170154968652',
    projectId: 'smart-expense-tracker-86619',
    storageBucket: 'smart-expense-tracker-86619.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChqJzuKcK1Do_BpbpuruA4LPF_xAS2Qpw',
    appId: '1:170154968652:ios:528b111ebd294d7005d6e9',
    messagingSenderId: '170154968652',
    projectId: 'smart-expense-tracker-86619',
    storageBucket: 'smart-expense-tracker-86619.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD--h9D9L_-B7bfjCDY9nOdyTVJCdp-PN4',
    appId: '1:170154968652:web:99692dfdb9bb2f9e05d6e9',
    messagingSenderId: '170154968652',
    projectId: 'smart-expense-tracker-86619',
    authDomain: 'smart-expense-tracker-86619.firebaseapp.com',
    storageBucket: 'smart-expense-tracker-86619.firebasestorage.app',
  );
}
